### ISSUE TITLE
Whether to support printing anonymous live broadcast room user ID

### ISSUE THREAD

**Issue by XXXXXY1** [InjoyDeng/BulletScreenCapturer#1]
I have a question, does it support printing out the user ID of the anonymous live broadcast room, and how to achieve it?

**Comment by InjoyDeng** [comment]
I haven't tried to enable anonymous nicknames in my livestream room, so I don’t know if the streamer can see the full name of the viewer’s nickname. If live streamer can’t see full name, I think this idea is impossible.
